language: python
cache: pip
matrix:
  include:
  - os: osx
    language: generic
  - python: pypy
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9
install:
  - scripts/travis.sh pip install --upgrade setuptools
  - scripts/travis.sh pip install --upgrade --requirement=requirements-travis.txt
  - scripts/travis.sh LC_ALL=C pip install .
script:
  - scripts/travis.sh make check
  - scripts/travis.sh make test
after_success:
  - scripts/travis.sh coveralls
branches:
  except:
    - /^[0-9]/
